import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "../components/profileContext/profile-content";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
      <body className={`antialiased`}>{children}</body>
      </UserProvider>
    </html>
  );
}
